// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ECzXnoxADkQLXZKhMqQjVZMDPZHCGyY',
    appId: '1:583694532210:web:aeeac2d5035ba008c8cceb',
    messagingSenderId: '583694532210',
    projectId: 'cs4750-project-9653f',
    authDomain: 'cs4750-project-9653f.firebaseapp.com',
    storageBucket: 'cs4750-project-9653f.firebasestorage.app',
    measurementId: 'G-2CXPBP2H32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLUcdmRP-do1Hs8u-58jxp6YzHMKA4gkU',
    appId: '1:583694532210:android:38ff2bf09411aa26c8cceb',
    messagingSenderId: '583694532210',
    projectId: 'cs4750-project-9653f',
    storageBucket: 'cs4750-project-9653f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4ECzXnoxADkQLXZKhMqQjVZMDPZHCGyY',
    appId: '1:583694532210:web:fda7ccda0f3a78a7c8cceb',
    messagingSenderId: '583694532210',
    projectId: 'cs4750-project-9653f',
    authDomain: 'cs4750-project-9653f.firebaseapp.com',
    storageBucket: 'cs4750-project-9653f.firebasestorage.app',
    measurementId: 'G-VCGQZE9TCT',
  );
}
